create extension if not exists pgcrypto;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'posts'
      and column_name = 'date'
  ) then
    alter table public.posts rename column date to legacy_date_text;
  end if;
end
$$;

alter table public.posts
  add column if not exists status text,
  add column if not exists published_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

update public.posts
set
  status = coalesce(status, 'published'),
  published_at = coalesce(
    published_at,
    case
      when legacy_date_text ~ '^[A-Z][a-z]{2} [0-9]{1,2}, [0-9]{4}$'
        then to_date(legacy_date_text, 'Mon DD, YYYY')::timestamp at time zone 'UTC'
      else created_at
    end
  ),
  updated_at = coalesce(updated_at, created_at, now())
where
  status is null
  or published_at is null
  or updated_at is null;

alter table public.posts
  alter column slug set not null,
  alter column status set not null,
  alter column status set default 'draft';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'posts_slug_non_empty'
  ) then
    alter table public.posts
      add constraint posts_slug_non_empty check (btrim(slug) <> '');
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'posts_slug_format'
  ) then
    alter table public.posts
      add constraint posts_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$');
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'posts_status_check'
  ) then
    alter table public.posts
      add constraint posts_status_check check (status in ('draft', 'published'));
  end if;
end
$$;

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row
execute function public.set_current_timestamp_updated_at();

create table if not exists public.admin_login_attempts (
  fingerprint text primary key,
  attempt_count integer not null default 0,
  first_attempt_at timestamptz not null default now(),
  last_attempt_at timestamptz not null default now(),
  blocked_until timestamptz
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  event_type text not null,
  success boolean not null default true,
  fingerprint text,
  ip_address text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key,
  email text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  bucket_id text not null default 'blog-assets',
  object_path text not null unique,
  mime_type text not null,
  byte_size bigint not null,
  owner_post_id bigint references public.posts(id) on delete set null,
  state text not null default 'draft',
  created_at timestamptz not null default now(),
  last_referenced_at timestamptz not null default now(),
  constraint media_assets_state_check check (state in ('draft', 'published', 'orphaned'))
);

create index if not exists media_assets_owner_post_id_idx on public.media_assets(owner_post_id);
create index if not exists media_assets_state_idx on public.media_assets(state);
create index if not exists media_assets_last_referenced_at_idx on public.media_assets(last_referenced_at);
create index if not exists admin_audit_log_event_type_created_at_idx on public.admin_audit_log(event_type, created_at desc);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'blog-assets',
  'blog-assets',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/avif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types,
  updated_at = now();
